name: Remove Agenda Label
on:
  workflow_dispatch:  # Manual trigger

jobs:
  remove_agenda_label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove Agenda Label
        run: |
          npm install @octokit/rest
          node -e "const { Octokit } = require('@octokit/rest');
          const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
          const owner = 'Adity20';
          const repo = 'testing';
          const issueNumber = 3;
          const labelToRemove = 'agenda';

          console.log('Attempting to remove label from issue...');
          
          octokit.issues.removeLabel({
            owner,
            repo,
            issue_number: issueNumber,
            name: labelToRemove
          })
          .then(response => {
            console.log('Label removed successfully:', response);
          })
          .catch(error => {
            console.error('Error removing label:', error.message);
            process.exit(1);
          });
          "
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
