name: Remove Agenda Label
on:
  workflow_dispatch:  # Manual trigger

jobs:
  remove_agenda_label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: npm install axios
      
      - name: Remove Agenda Label
        run: |
          const axios = require('axios');

          const owner = 'Adity20';
          const repo = 'testing';
          const issueNumber = 4;
          const labelToRemove = 'agenda';
          const token = process.env.GITHUB_TOKEN;

          const query = `
            mutation RemoveLabel($input: RemoveLabelsFromLabelableInput!) {
              removeLabelsFromLabelable(input: $input) {
                clientMutationId
              }
            }
          `;

          const variables = {
            input: {
              labelableId: issueNumber,
              labelIds: [labelToRemove],
            },
          };

          axios.post(`https://api.github.com/graphql`, {
            query: query,
            variables: variables
          }, {
            headers: {
              Authorization: `Bearer ${token}`
            }
          })
          .then(response => {
            console.log('Label removed successfully:', response.data.data);
          })
          .catch(error => {
            console.error('Error removing label:', error.message);
            process.exit(1);
          });
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
