name: Remove Agenda Label
on:
  workflow_dispatch:

jobs:
  remove_agenda_label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove Agenda Label
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const { graphql } = require('@actions/github');
            const octokit = new github.GitHub(process.env.GITHUB_TOKEN);

            const owner = 'Adity20';
            const repo = 'testing';
            const issueNumber = 2;
            const labelToRemove = 'agenda';

            // GraphQL query to get the issue labels
            const query = `
              query ($owner: String!, $repo: String!, $issueNumber: Int!) {
                repository(owner: $owner, name: $repo) {
                  issue(number: $issueNumber) {
                    labels(first: 100) {
                      nodes {
                        name
                      }
                    }
                  }
                }
              }
            `;

            // Variables for the GraphQL query
            const variables = {
              owner: owner,
              repo: repo,
              issueNumber: issueNumber
            };

            // Execute GraphQL query
            const { repository } = await graphql(query, variables);

            // Extract label names
            const labels = repository.issue.labels.nodes.map(label => label.name);

            // Check if the label to remove exists
            if (labels.includes(labelToRemove)) {
              // Remove the label
              const newLabels = labels.filter(label => label !== labelToRemove);
              await octokit.issues.setLabels({
                owner: owner,
                repo: repo,
                issue_number: issueNumber,
                labels: newLabels
              });
            }
